### ISSUE TITLE
Inconsistency between primary main.tf and other versions in exercises directory

### ISSUE THREAD

**Issue by rberlind** [hashicorp/hashicat-aws#6]
There is an inconsistency in hashicat-aws between main.tf in main folder and the 3 main.tf files in exercises. tls_private_key.hashicat in first has `private_key_filename = "${random_id.app-server-id.dec}-ssh-key.pem"`, but other 3 files have `private_key_filename = "${var.prefix}-ssh-key.pem"`

**Comment by rberlind** [comment]
We can probably get rid of the random_id resource and just use `var.prefix` in all 4 files.

**Comment by rberlind** [comment]
Note that the hashicat-azure and hashicat-gcp apps do not use the random_id resource

**Comment by scarolan** [comment]
Do you remember why we added this to begin with?
https://github.com/hashicorp/hashicat-aws/commit/7460606a1936b7f130313b461f15a9d93b29b7dd

Perhaps to avoid a file naming conflict somewhere?

**Comment by rberlind** [comment]
No idea.  I suspect I did that PR to actually use the random_id resource.

**Comment by rberlind** [comment]
random_id resource was added by Neil Dahlke when he tried to add Route53, but that had to be removed because Instruqt did not have access to HashiCorp's Route53 domain.  It looks like the random_id resource was left behind and that I decided to use it rather than delete it.  So, I think we should delete it.
